name: Jekyll site CI & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Pages (registers Pages deployment)
        uses: actions/configure-pages@v5

      - name: Build the site in the jekyll/builder container
        run: |
          # ensure workspace directories exist
          mkdir -p _site
          # run docker build; note: each backslash must be the final character on the line
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/srv/jekyll" \
            -v "${GITHUB_WORKSPACE}/_site:/srv/jekyll/_site" \
            jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show deployed URL
        run: echo "Pages URL: ${{ steps.deployment.outputs.page_url }}"
